### PR TITLE
Add a widget and hide page from page list and fix #10

### LINKED ISSUE #10: some bugs in server time

### PR DESCRIPTION
**Pull request by julien-gargot**
It is a raw improvement, more to start something than a finality.

### CODE REVIEW

**Comment by louis-ev** [comment]
Thanks ! Got to try it but it looks good already !
Not sure about the `hide: true` for the blueprint though?

**Comment by julien-gargot** [comment]
It seams to be an issue with the timer counter per user between page visits, but I have check one more time.

About the `hide:true`, I had the feeling that it is less confusing for admins to access logs through a widget than a page. To not have to choose, it can be an option :) `c::set(…`

**Comment by louis-ev** [comment]
Yes ! It makes sense if the widget allows for accessing all months, even a few years down the line. Will check your PR soon, thanks!

**Comment by julien-gargot** [comment]
Screen shot of widget

To be more precise: I hide kirby tracking page from the pages list, and granted its access through the widget, with a link.

**Pull request merged**
